version: '3'

services:
  password_generator:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: pass_gen
    volumes:
      - .:/app
    ports:
      - "8000:8000"